title: HumHub Weather Module
description: Weather widget for humhub community platform.
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/zauberware/humhub-weather-module/zipball/master
  tar_url: https://github.com/zauberware/humhub-weather-module/tarball/master