title: HumHub Weather Module
description: Weather widget for humhub community platform.
show_downloads: true
theme: jekyll-theme-cayman
download: https://github.com/zauberware/humhub-weather-module/archive/master.zip
